### ISSUE TITLE
Hello-World (Resouce Categorization)

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#105]
Define how to show resource categorization functionality for hello-world test

needs mF2C/ResourceManagement#12

**Comment by fcarp10** [comment]
We skip for now Resource Categorization for f2f demo. No updates since the last demo in Brussels.

**Comment by ALEJANDROJ19** [comment]
We got an error while testing the flow with all the other modules. 

```
resource-categorization   | Dynamic: {"device": "0f848d8fb78cbe5615507ef5a198f660ac89a3ae03b95e79d4ebfb3466c20d54e9a5d9b9c41f88c782d1f67b32231d31b4fada8d2f9dd31a4d884681b784ec5a", "ramFree": 3480.93359375, "ramFreePercent": 43.6, "storageFree": 24087.3046875, "storageFreePercent": 63.4, "cpuFreePercent": 89.6, "powerRemainingStatus": "100.0", "powerRemainingStatusSeconds": "BatteryTime.POWER_TIME_UNLIMITED", "ethernetAddress": "[snicaddr(family=<AddressFamily.AF_INET: 2>, address='172.19.0.11', netmask='255.255.0.0', broadcast='172.19.255.255', ptp=None), snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='02:42:ac:13:00:0b', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]", "wifiAddress": "Empty", "ethernetThroughputInfo": ["33550", "18243", "142", "146", "0", "0", "0", "0"], "wifiThroughputInfo": ["E", "m", "p", "t", "y"], "myLeaderID": "None"}
cimi                      | java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IPersistentMap
cimi                      |     at clojure.lang.RT.dissoc(RT.java:884)
cimi                      |     at clojure.core$dissoc.invokeStatic(core.clj:1503)
cimi                      |     at clojure.core$dissoc.invokeStatic(core.clj:1496)
cimi                      |     at clojure.core$dissoc.doInvoke(core.clj:1496)
cimi                      |     at clojure.lang.RestFn.invoke(RestFn.java:521)
cimi                      |     at com.sixsq.slipstream.ssclj.resources.common.utils$strip_service_attrs.invokeStatic(utils.clj:74)
cimi                      |     at com.sixsq.slipstream.ssclj.resources.common.utils$strip_service_attrs.invoke(utils.clj:69)
cimi                      |     at com.sixsq.slipstream.ssclj.resources.common.std_crud$add_fn$fn__3342.invoke(std_crud.clj:30)
cimi                      |     at com.sixsq.slipstream.ssclj.resources.device_dynamic$eval22208$fn__22209.invoke(device_dynamic.clj:43)
cimi                      |     at clojure.lang.MultiFn.invoke(MultiFn.java:229)
cimi                      |     at com.sixsq.slipstream.ssclj.app.routes$fn__2638$fn__2639.invoke(routes.clj:17)
cimi                      |     at compojure.core$wrap_response$fn__2488.invoke(core.clj:158)
cimi                      |     at compojure.core$wrap_route_middleware$fn__2472.invoke(core.clj:128)
cimi                      |     at compojure.core$wrap_route_info$fn__2477.invoke(core.clj:137)
cimi                      |     at compojure.core$wrap_route_matches$fn__2481.invoke(core.clj:146)
cimi                      |     at compojure.core$routing$fn__2496.invoke(core.clj:185)
cimi                      |     at clojure.core$some.invokeStatic(core.clj:2693)
cimi                      |     at clojure.core$some.invoke(core.clj:2684)
cimi                      |     at compojure.core$routing.invokeStatic(core.clj:185)
cimi                      |     at compojure.core$routing.doInvoke(core.clj:182)
cimi                      |     at clojure.lang.RestFn.applyTo(RestFn.java:139)
cimi                      |     at clojure.core$apply.invokeStatic(core.clj:659)
cimi                      |     at clojure.core$apply.invoke(core.clj:652)
cimi                      |     at compojure.core$routes$fn__2500.invoke(core.clj:192)
cimi                      |     at compojure.core$routing$fn__2496.invoke(core.clj:185)
cimi                      |     at clojure.core$some.invokeStatic(core.clj:2693)
cimi                      |     at clojure.core$some.invoke(core.clj:2684)
cimi                      |     at compojure.core$routing.invokeStatic(core.clj:185)
cimi                      |     at compojure.core$routing.doInvoke(core.clj:182)
cimi                      |     at clojure.lang.RestFn.applyTo(RestFn.java:139)
cimi                      |     at clojure.core$apply.invokeStatic(core.clj:659)
cimi                      |     at clojure.core$apply.invoke(core.clj:652)
cimi                      |     at compojure.core$routes$fn__2500.invoke(core.clj:192)
cimi                      |     at com.sixsq.slipstream.ssclj.middleware.cimi_params$wrap_cimi_params$fn__2813.invoke(cimi_params.clj:59)
cimi                      |     at com.sixsq.slipstream.ssclj.middleware.base_uri$wrap_base_uri$fn__2707.invoke(base_uri.clj:40)
cimi                      |     at ring.middleware.keyword_params$wrap_keyword_params$fn__3812.invoke(keyword_params.clj:36)
cimi                      |     at ring.middleware.nested_params$wrap_nested_params$fn__3870.invoke(nested_params.clj:89)
cimi                      |     at ring.middleware.params$wrap_params$fn__3894.invoke(params.clj:67)
cimi                      |     at com.sixsq.slipstream.ssclj.middleware.exception_handler$wrap_exceptions$fn__2937.invoke(exception_handler.clj:18)
cimi                      |     at com.sixsq.slipstream.ssclj.middleware.authn_info_header$wrap_authn_info_header$fn__2025.invoke(authn_info_header.clj:89)
cimi                      |     at metrics.ring.expose$expose_metrics_as_json$fn__3562.invoke(expose.clj:138)
cimi                      |     at ring.middleware.json$wrap_json_body$fn__3747.invoke(json.clj:44)
cimi                      |     at ring.middleware.json$wrap_json_response$fn__3772.invoke(json.clj:87)
cimi                      |     at metrics.ring.instrument$handle_request$fn__3582.invoke(instrument.clj:65)
cimi                      |     at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
cimi                      |     at com.codahale.metrics.Timer.time(Timer.java:101)
cimi                      |     at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
cimi                      |     at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
cimi                      |     at metrics.ring.instrument$instrument$fn__3590.invoke(instrument.clj:91)
cimi                      |     at com.sixsq.slipstream.ssclj.middleware.logger$wrap_logger$fn__2965.invoke(logger.clj:60)
cimi                      |     at ring.middleware.cookies$wrap_cookies$fn__3716.invoke(cookies.clj:175)
cimi                      |     at aleph.http.server$handle_request$fn__14317$f__4340__auto____14318.invoke(server.clj:157)
cimi                      |     at clojure.lang.AFn.run(AFn.java:22)
cimi                      |     at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
cimi                      |     at manifold.executor$thread_factory$reify__4222$f__4223.invoke(executor.clj:44)
cimi                      |     at clojure.lang.AFn.run(AFn.java:22)
cimi                      |     at java.lang.Thread.run(Thread.java:748)
resource-categorization   | r <Response [500]> <PreparedRequest [POST]> Internal Server Error
```

Any idea @cjdcordeiro  (contact with @ssgUPC pls).

**Comment by ssgUPC** [comment]
@cjdcordeiro , @fcarp10 & @ALEJANDROJ19 please try with the following docker image for the resource categorization latest-V.2.0.6                                                                               

I hope you'll not get any more problem regarding my resource-categorization component. If you still have some issues, then please let me know. I'll try my best to solve it. 

P.S. - The error was the data-type of deviceID was not matching with the expected CIMI resources, so I have already fixed it in the new version of docker-image.

**Comment by fcarp10** [comment]
@ssgUPC, @ALEJANDROJ19, please create a new branch with your changes. Whenever is working, then create a PR. Thanks!

**Comment by ALEJANDROJ19** [comment]
Done. Resource-categorization is working, integrated and tested.

Latest stable version: mf2c/resource-categorization:latest-V2.0.7

Known issues:
- device-dynamic resource is created multiple times.
